# Preprocessing

In [1]:
! pip install -r requirements.txt -q

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('./data/dataset.csv')

In [3]:
df.head()

,DATE_TIME,TOTAL_DEMAND,RRP,PUBLIC_HOLIDAY,SCHOOL_HOLIDAY,TEMPERATURE,DWPC,HUMIDITY,APPARENT_TEMP,WIND_SPEED,CLOUD_COVER,CASH_RATE,HOUSEHOLD_SPEND,SPEND_GROWTH,CONF_IDX,NSW_POPULATION,ROOFTOP_SOLAR_MW,GROSS_DEMAND_MW
0,2022-01-01 00:00:00,7206.03,124.86,True,True,23.0,16.0,64.69,23.0,27.780,2.0,0.1,18099.6,-16.0,101.4,8110610,0.0,7206.03
1,2022-01-01 00:10:00,7174.26,126.02,True,True,23.0,16.0,64.69,23.0,25.928,2.0,0.1,18099.6,-16.0,101.4,8110665,0.0,7174.26
2,2022-01-01 00:20:00,7065.84,113.54,True,True,23.0,16.0,64.69,23.0,24.076,2.0,0.1,18099.6,-16.0,101.4,8110720,0.0,7065.84
3,2022-01-01 00:30:00,6988.47,124.06,True,True,23.0,16.0,64.69,23.0,22.224,2.0,0.1,18099.6,-16.0,101.4,8110775,0.0,6988.47
4,2022-01-01 00:30:00,6988.47,124.06,True,True,23.0,16.0,64.69,23.0,22.224,2.0,0.1,18099.6,-16.0,101.4,8110775,0.0,6988.47

In [4]:
print(df.shape)
df.info()
df.describe()

(29769, 18)
<class 'pandas.DataFrame'>
RangeIndex: 29769 entries, 0 to 29768
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATE_TIME         29769 non-null  str
 1   TOTAL_DEMAND      29769 non-null  float64
 2   RRP               29769 non-null  float64
 3   PUBLIC_HOLIDAY    29769 non-null  bool
 4   SCHOOL_HOLIDAY    29769 non-null  bool
 5   TEMPERATURE       29769 non-null  float64
 6   DWPC              29769 non-null  float64
 7   HUMIDITY          29769 non-null  float64
 8   APPARENT_TEMP     29769 non-null  float64
 9   WIND_SPEED        29769 non-null  float64
 10  CLOUD_COVER       29769 non-null  float64
 11  CASH_RATE         29769 non-null  float64
 12  HOUSEHOLD_SPEND   29769 non-null  float64
 13  SPEND_GROWTH      29769 non-null  float64
 14   CONF_IDX         29769 non-null  float64
 15  NSW_POPULATION    29769 non-null  int64
 16  ROOFTOP_SOLAR_MW  29769 non-null  float64
 17  GROSS_DEMAND_MW   29769 non-null  float64
dtypes: bool(2), float64(14), int64(1), str(1)
memory usage: 4.2 MB

,TOTAL_DEMAND,RRP,TEMPERATURE,DWPC,HUMIDITY,APPARENT_TEMP,WIND_SPEED,CLOUD_COVER,CASH_RATE,HOUSEHOLD_SPEND,SPEND_GROWTH,CONF_IDX,NSW_POPULATION,ROOFTOP_SOLAR_MW,GROSS_DEMAND_MW
count,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,29769.000000,2.976900e+04,29769.000000,29769.000000
mean,7437.368198,80.317015,23.288701,17.854491,73.116913,23.429797,22.565670,4.255487,3.100118,21869.871228,-12.677094,88.298841,8.477012e+06,1155.177165,8592.545363
std,1265.342262,297.552097,3.115093,2.481602,13.729186,3.344934,10.935047,2.637844,1.573166,2042.424190,1.873287,6.744849,1.417329e+05,1479.870726,1750.892179
min,4050.180000,-999.990000,15.000000,5.000000,12.500000,15.000000,0.000000,0.000000,0.100000,17983.300000,-16.000000,78.700000,8.110610e+06,0.000000,5660.320000
25%,6548.390000,52.920000,21.000000,16.000000,64.260000,21.000000,13.581300,2.000000,3.100000,21629.700000,-13.400000,84.000000,8.390295e+06,0.000000,7169.990000
50%,7274.560000,72.680000,23.000000,18.000000,73.610000,23.000000,21.606700,6.000000,3.600000,22511.800000,-11.700000,86.600000,8.542276e+06,348.238000,8441.653700
75%,8115.030000,92.010000,25.000000,20.000000,83.210000,25.000000,29.632000,6.000000,4.350000,23055.700000,-11.500000,86.900000,8.592524e+06,2101.020700,9671.605000
max,13137.470000,17500.000000,42.000000,24.000000,100.000000,42.294400,77.784000,8.000000,4.350000,24053.600000,-0.600000,101.400000,8.592524e+06,6509.900000,15885.705000

In [5]:
df.head()

,DATE_TIME,TOTAL_DEMAND,RRP,PUBLIC_HOLIDAY,SCHOOL_HOLIDAY,TEMPERATURE,DWPC,HUMIDITY,APPARENT_TEMP,WIND_SPEED,CLOUD_COVER,CASH_RATE,HOUSEHOLD_SPEND,SPEND_GROWTH,CONF_IDX,NSW_POPULATION,ROOFTOP_SOLAR_MW,GROSS_DEMAND_MW
0,2022-01-01 00:00:00,7206.03,124.86,True,True,23.0,16.0,64.69,23.0,27.780,2.0,0.1,18099.6,-16.0,101.4,8110610,0.0,7206.03
1,2022-01-01 00:10:00,7174.26,126.02,True,True,23.0,16.0,64.69,23.0,25.928,2.0,0.1,18099.6,-16.0,101.4,8110665,0.0,7174.26
2,2022-01-01 00:20:00,7065.84,113.54,True,True,23.0,16.0,64.69,23.0,24.076,2.0,0.1,18099.6,-16.0,101.4,8110720,0.0,7065.84
3,2022-01-01 00:30:00,6988.47,124.06,True,True,23.0,16.0,64.69,23.0,22.224,2.0,0.1,18099.6,-16.0,101.4,8110775,0.0,6988.47
4,2022-01-01 00:30:00,6988.47,124.06,True,True,23.0,16.0,64.69,23.0,22.224,2.0,0.1,18099.6,-16.0,101.4,8110775,0.0,6988.47

## Feature Engineering

In [6]:
df['DATE_TIME'] = pd.to_datetime(df['DATE_TIME'])

df['hour'] = df['DATE_TIME'].dt.hour
df['day_of_week'] = df['DATE_TIME'].dt.dayofweek
df['min_sin'] = np.sin(2 * np.pi * df['DATE_TIME'].dt.minute / 60)
df['min_cos'] = np.cos(2 * np.pi * df['DATE_TIME'].dt.minute / 60)
df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
df['month'] = df['DATE_TIME'].dt.month

def get_season(month):
    if month in [12, 1, 2]:
        return 'Summer'
    elif month in [3, 4, 5]:
        return 'Autumn'
    elif month in [6, 7, 8]:
        return 'Winter'
    else:
        return 'Spring'
    
df['season'] = df['month'].apply(get_season)
df = pd.get_dummies(df, columns=['season'], prefix='season')

df.drop(columns=['DATE_TIME'], inplace=True, errors='ignore')

In [7]:
## Splitting the Dataset

from sklearn.model_selection import train_test_split

y_target = "GROSS_DEMAND_MW"  # set the target variable

df.drop(columns=[
    'TOTAL_DEMAND',
    'ROOFTOP_SOLAR_MW'
], inplace=True, errors='ignore')

X_train, X_temp = train_test_split(df, test_size=0.4, random_state=42)
X_val, X_test = train_test_split(X_temp, test_size=0.5, random_state=42)

y_train, y_val, y_test = (
    X_train.pop(y_target),
    X_val.pop(y_target),
    X_test.pop(y_target),
)

df_names = ['X_train', 'X_val', 'X_test']

In [8]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(17861, 21)
(5954, 21)
(5954, 21)

## Data Transformation

### One-hot Encoding (OHE)

In [9]:
from sklearn.preprocessing import OneHotEncoder

ohe_encoder = OneHotEncoder()

for name in df_names:
    df_ = globals()[name]

    globals()[name] = df_.copy()

### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numeric_cols = X_train.select_dtypes(include=['number']).columns

scaler.fit(X_train[numeric_cols])

for name in df_names:
    df_ = globals()[name]
    
    df_[numeric_cols] = scaler.transform(df_[numeric_cols])

    for col in df_.columns:
        if df_[col].dtype == 'bool':
            df_[col] = df_[col].astype('category').cat.codes    

    globals()[name] = df_.copy()

In [11]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 17861 entries, 3462 to 23654
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RRP              17861 non-null  float64
 1   PUBLIC_HOLIDAY   17861 non-null  int8
 2   SCHOOL_HOLIDAY   17861 non-null  int8
 3   TEMPERATURE      17861 non-null  float64
 4   DWPC             17861 non-null  float64
 5   HUMIDITY         17861 non-null  float64
 6   APPARENT_TEMP    17861 non-null  float64
 7   WIND_SPEED       17861 non-null  float64
 8   CLOUD_COVER      17861 non-null  float64
 9   CASH_RATE        17861 non-null  float64
 10  HOUSEHOLD_SPEND  17861 non-null  float64
 11  SPEND_GROWTH     17861 non-null  float64
 12   CONF_IDX        17861 non-null  float64
 13  NSW_POPULATION   17861 non-null  float64
 14  hour             17861 non-null  float64
 15  day_of_week      17861 non-null  float64
 16  min_sin          17861 non-null  float64
 17  min_cos          17861 non-null  float64
 18  is_weekend       17861 non-null  float64
 19  month            17861 non-null  float64
 20  season_Summer    17861 non-null  int8
dtypes: float64(18), int8(3)
memory usage: 2.6 MB

### Target value log transform

## Modelling

In [12]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression(
    fit_intercept=True
)

lin_reg.fit(X_train, y_train)

lin_train_preds = lin_reg.predict(X_train)
lin_val_preds = lin_reg.predict(X_val)
lin_test_preds = lin_reg.predict(X_test)

In [13]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb_model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=False
)

xgb_train_preds = xgb_model.predict(X_train)
xgb_val_preds = xgb_model.predict(X_val)
xgb_test_preds = xgb_model.predict(X_test)

In [14]:
from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_state=42
)

cat_model.fit(
    X_train, y_train,
    eval_set=(X_val, y_val),
    early_stopping_rounds=50,
    verbose=False
)

cat_train_preds = cat_model.predict(X_train)
cat_val_preds = cat_model.predict(X_val)
cat_test_preds = cat_model.predict(X_test)

In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd

def get_metrics(y_true, y_pred, name):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    
    return {
        'Model': name,
        'RMSE (MW)': round(rmse, 2),
        'MAE (MW)': round(mae, 2),
        'R2 Score': round(r2, 4)
    }


results = [
    get_metrics(y_test, lin_test_preds, "Linear Regression"),
    get_metrics(y_test, xgb_test_preds, "XGBoost"),
    get_metrics(y_test, cat_test_preds, "CatBoost")
]

metrics_df = pd.DataFrame(results)
display(metrics_df)

               Model  RMSE (MW)  MAE (MW)  R2 Score
0  Linear Regression     881.64    706.10    0.7514
1            XGBoost     174.83    120.50    0.9902
2           CatBoost     208.81    149.12    0.9861